version: '3.8'
services:
  cache:
    image: redis

  app:
    build:
      context: ./
    env_file:
      - .env
    depends_on:
      - cache
    ports:
      - 4000:4000
    environment:
      REDIS_URL: redis://cache

  syncer:
    build:
      context: ./
    env_file:
      - .env
    depends_on:
      - cache
    command: ["python", "-m", "app.pairs.syncer"]
    environment:
      REDIS_URL: redis://cache
